package xfire;

import java.sql.SQLException;
//Generated by MyEclipse
import java.util.Vector;

public interface IXfireAPI {
	
	public String getUsers(String name, String cardNum);
	public int Number();
	public String userUnit(int id);
	public String[] userProfile(int id);
	public String[] userSelectThingFuzzy(String name);
	public String userSelectThingAccurate(int id);
	public void userDeleteThing(int id);
	public int userAdd(String[] lis);
	public void userAddEquipment(String[] lis);
	public void userUpdate(int id,String[] lis);
}